const $=s=>document.querySelector(s),norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18N={ca:{source:'Calendaris contrastats amb JOK.cat',season:'TEMPORADA 2026–27',headline:'Les categories de la UE Horta<br><em>i els seus clubs rivals</em>',lead:'Cerca per club, ciutat o localitat. Obre qualsevol fitxa i calcula la ruta des de la teva ubicació amb Google Maps.',searchPlaceholder:'Cerca per club, ciutat, localitat o adreça…',searchButton:'Cercar',categories:'categories',teamsListed:'equips llistats',seasonShort:'temporada',sourcesTitle:'Fonts i criteri',sourcesText:"Les categories s'han contrastat amb JOK.cat. Les adreces i telèfons s'han incorporat només quan s'han pogut contrastar amb una font publicada.",phone:'Telèfon no disponible',maps:'↗ Obre la ruta a Google Maps',none:"No s'ha trobat cap club o localitat.",masc:'Masculí',fem:'Femení'},es:{source:'Calendarios contrastados con JOK.cat',season:'TEMPORADA 2026–27',headline:'Las categorías de la UE Horta<br><em>y sus clubes rivales</em>',lead:'Busca por club, ciudad o localidad. Abre cualquier ficha y calcula la ruta desde tu ubicación con Google Maps.',searchPlaceholder:'Busca por club, ciudad, localidad o dirección…',searchButton:'Buscar',categories:'categorías',teamsListed:'equipos listados',seasonShort:'temporada',sourcesTitle:'Fuentes y criterio',sourcesText:'Las categorías se han contrastado con JOK.cat. Las direcciones y teléfonos solo se incorporan cuando se han podido contrastar con una fuente publicada.',phone:'Teléfono no disponible',maps:'↗ Abrir la ruta en Google Maps',none:'No se ha encontrado ningún club o localidad.',masc:'Masculino',fem:'Femenino'}};
let lang=localStorage.getItem('hockeyHortaLang')||'ca',t=I18N[lang],teams=DATA.categories.flatMap(c=>c.teams);$('#catCount').textContent=DATA.categories.length;$('#clubCount').textContent=new Set(teams.map(x=>x.name)).size;
function apply(){t=I18N[lang];document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(e=>e.innerHTML=t[e.dataset.i18n]??'');document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=t[e.dataset.i18nPlaceholder]??'');document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('hockeyHortaLang',lang);render($('#search').value)}
function initials(n){return String(n).replace(/[^A-Za-zÀ-ÿ0-9 ]/g,'').split(/\s+/).filter(Boolean).slice(0,3).map(x=>x[0]).join('').toUpperCase()}
function searchable(x,cat){return norm([x.name,x.city,x.address,x.phone,cat.name,cat.official,cat.gender].filter(Boolean).join(' '))}
function render(q=''){const query=norm(q),root=$('#results');root.innerHTML='';let shown=0;DATA.categories.forEach((cat,i)=>{const ts=cat.teams.filter(x=>!query||searchable(x,cat).includes(query));if(!ts.length)return;shown++;const gender=cat.gender==='Masculí'?t.masc:cat.gender==='Femení'?t.fem:cat.gender;const a=document.createElement('article');a.className='category'+(query?' open':'');a.innerHTML=`<button class="cat-head" type="button"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="cat-title"><strong>${esc(cat.name)}</strong><small>${esc(gender)} · ${ts.length} ${t.teamsListed}</small></span><span class="chev">⌄</span></button><div class="teams">${ts.map(x=>`<div class="team"><div class="shield">${x.logo?`<img src="${esc(x.logo)}" alt="${lang==='ca'?'Escut':'Escudo'} de ${esc(x.name)}" loading="lazy">`:esc(initials(x.name))}</div><div class="teaminfo"><strong>${esc(x.name)}</strong><small class="address">${esc(x.address||'—')}</small>${x.phone?`<a class="phone" href="tel:${esc(x.phone.replace(/[^0-9+]/g,''))}">☎ ${esc(x.phone)}</a>`:`<small class="phone unavailable">☎ ${t.phone}</small>`}<a class="maps" href="${esc(x.maps)}" target="_blank" rel="noopener noreferrer">${t.maps}</a></div></div>`).join('')}</div>`;a.querySelector('.cat-head').onclick=()=>a.classList.toggle('open');root.appendChild(a)});if(!shown)root.innerHTML=`<div class="empty">${t.none}</div>`}
function doSearch(){render($('#search').value);$('#results').scrollIntoView({behavior:'smooth',block:'start'})}
document.querySelectorAll('.lang-btn').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;apply()}));$('#search').addEventListener('input',e=>render(e.target.value));$('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();doSearch()}});$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();doSearch()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus();$('#search').select()}});apply();
